# Generated by Django 5.2.7 on 2025-11-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='code',
            field=models.CharField(default='xxx', max_length=10),
        ),
    ]
